clc;
clear all;
close all;
x=input('Enter the 1st sequence');
h=input('Enter the 2nd sequence');
y=conv(x,h);
figure;
subplot(3,1,1);
stem(x);
ylabel('Amplitude--.');
xlabel('(a)n--.');
title('first sequence');
subplot(3,1,2);
stem(h);
ylabel('Amplitude');
xlabel('(b)n--.');
title('second sequence');
subplot(3,1,3);
stem(y);
ylabel('Amplitude--.');
xlabel('(c)n--.');
title('Convoluted sequence');
disp('the resultant signal is');
